### ISSUE TITLE
Pathfinding

### ISSUE THREAD

**Issue by valanths1990** [L2J/L2J_Server#183] opened 2015-12-15 07:21 UTC
I tested with latest develop

http://prntscr.com/9eckhn

char does not start movenent
he must be close otherwise cannot attack

maybe same issue with this: https://github.com/L2J/L2J_Server/issues/177

**Comment by HorridoJoho** [comment] 2015-12-30 12:03
Duplicate of #177

**Closed by HorridoJoho** 2015-12-30 12:03 UTC
Labels: BUG, DUPLICATE, HIGH FIVE, UNCONFIRMED
